class-work/games/config/routes.rb
Games::Application.routes.draw do


  root 'games#index'
  
  resources 'games', only: [:index]
  resources "secret_numbers", only: [:new, :show]
  resources "rock_papers", only: [:new, :show]
  resources "scrambles", only: [:new, :show]
end

class-work/games/app/models/word.rb
class Word
	attr_accessor :name
  
  def initialize(name)
    self.name = name
  end
  
  # Word.random
  def self.random(options={})

    # Defaults
    options.reverse_merge!(
      :min_corpus_count => 1000,
      :min_dictionary_count => 50,
      :limit => 1
    )
    
    # Get back an array of hashes that look like {"id"=>92367, "word"=>"resist"} 
    # and turn them into Word objects:
    words = Wordnik.words.get_random_words(options).map{|obj| Word.new(obj['word']) }
    
    # Return one or many?
    options[:limit] == 1 ? words.first : words
  end

end

class-work/games/app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
  end
end

class-work/games/app/controllers/rock_papers_controller.rb
class RockPapersController < ApplicationController
  def new
  end

  def show
    @player_throw = params[:id].to_i
    @robot_throw = rand(0..2)

    compare_hands(@player_throw,@robot_throw)
  end

  def compare_hands(player,robot)
  	case[player,robot]
      when [0,0],[1,1],[2,2]
  		@outcome_partial = 'tie' 
  	 when [0,1],[2,0],[1,2]
  		@outcome_partial = 'lose'
    else
      @outcome_partial = 'win'
    end
  end
end

class-work/games/app/controllers/scrambles_controller.rb
class ScramblesController < ApplicationController
  def new
  	words = Word.random
  	@random_word = words.name

  	def string_shuffle(s)
  		s.split("").shuffle.join
		end

		@scrambled_word	= string_shuffle(@random_word)
  end

  def show
		@guess = params[:guess]
		@word = params[:word]

		if @guess.upcase == @word.upcase
			@outcome_partial = 'win'
		else
			@outcome_partial = 'lose'
		end	
  end
end

class-work/games/app/controllers/secret_numbers_controller.rb
class SecretNumbersController < ApplicationController
  def new
  end

  def show
    @chosen_number = params[:id].to_i
    @secret_number = rand(1..5)
    @player_won = (@chosen_number == @secret_number)

    if @player_won
      @outcome_partial = 'win'
    else
      @outcome_partial = 'lose'
    end
  end
end

class-work/games/app/helpers/games_helper.rb
module GamesHelper
end

class-work/games/app/helpers/rock_papers_helper.rb
module RockPapersHelper
end

class-work/games/app/helpers/scrambles_helper.rb
module ScramblesHelper
end

class-work/games/app/helpers/secret_numbers_helper.rb
module SecretNumbersHelper
end

class-work/games/app/views/games/index.html.erb
<div class="game-center">
	<h1>Welcome to the Game Center</h1>
	<h3>Choose a game below to get started:</h3>

	<div class="games">
		<%= link_to(image_tag("games/secret-number.jpg"), new_secret_number_path) %>
		<%= link_to(image_tag("games/rock-paper-scissors.jpg"), new_rock_paper_path) %>
		<%= link_to(image_tag("scramble/scramble.png"), new_scramble_path) %>
	</div>
</div>

class-work/games/app/views/secret_numbers/new.html.erb
<div class="all-games-link">
	<%= link_to 'BACK TO ALL GAMES', root_path %>
</div>

<div class="game-center">	
	<h1>Welcome to Secret Number!</h1>
	<p>To play this game, all you have to do is guess a number. <br>If you guess the
	  <em>secret number</em>, you win!</p>
	<p>Choose carefully... you only get one try!</p>
	<h2>Pick a number:</h2>
	<div class="choose-hand">
	  <% 1.upto(5) do |number| %>
	    <div class="num-container">
	    	<%= link_to image_tag("secret_numbers/#{number}.jpeg"), secret_number_path(number) %>
	    </div>
	  <% end %>
	</div>
</div>

class-work/games/app/views/secret_numbers/show.html.erb
<div class="all-games-link">
	<%= link_to 'BACK TO ALL GAMES', root_path %>
</div>

<div class="game-center">
	<%= render @outcome_partial %>

	<h4>The secret number was <%= @secret_number %></h4>
	
	<h3 class="play-again"><%= link_to "PLAY AGAIN", new_secret_number_path %></h3>
</div>