class-work/museum_app/config/routes.rb
Rails.application.routes.draw do
  root 'app_homes#index'

  resources :app_homes, only: [:index]
  resources :museums, except: [:destory]
  resources :artists, except: [:destory]
  resources :paintings, except: [:destory]
end

class-work/museum_app/app/models/artist.rb
class Artist < ActiveRecord::Base
	has_many :paintings
end

class-work/museum_app/app/models/museum.rb
class Museum < ActiveRecord::Base
	has_many :paintings
	has_many :artists, through: :paintings
end

class-work/museum_app/app/models/painting.rb
class Painting < ActiveRecord::Base
	belongs_to :artist
	has_one :museum
end

class-work/museum_app/app/controllers/app_homes_controller.rb
class AppHomesController < ApplicationController
  def index
  end
end

class-work/museum_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

class-work/museum_app/app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def new
  end

  def show
    @artist = Artist.find(params[:id])
    @paintings = Painting.where(artist_id:(params[:id]))
  end

  def create
  end

  def edit
  end

  def update
  end
end

class-work/museum_app/app/controllers/museums_controller.rb
class MuseumsController < ApplicationController
  def index
    @museums = Museum.all
  end

  def new
  end

  def show
    @museum = Museum.find(params[:id])
    @paintings = Painting.where(museum_id:(params[:id]))
  end

  def create
  end

  def edit
  end

  def update
  end
end

class-work/museum_app/app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
  def index
    @paintings = Painting.all
  end

  def new
  end

  def show
  end

  def create
  end

  def edit
  end

  def update
  end
end

class-work/museum_app/app/helpers/app_homes_helper.rb
module AppHomesHelper
end

class-work/museum_app/app/helpers/application_helper.rb
module ApplicationHelper
end

class-work/museum_app/app/helpers/artists_helper.rb
module ArtistsHelper
end

class-work/museum_app/app/helpers/museums_helper.rb
module MuseumsHelper
end

class-work/museum_app/app/helpers/paintings_helper.rb
module PaintingsHelper
end

class-work/museum_app/app/views/app_homes/_nav.html.erb
<h1>MuseumPaintings</h1>
<h3>View paintings from around the world.</h3>
<br>
<%= link_to 'Home', root_path %>
<br>
<br>
<br>

class-work/museum_app/app/views/app_homes/index.html.erb
<%= render partial: "app_homes/nav" %>


<%= link_to '<button type="button">All Museums</button>'.html_safe, museums_path %>

<%= link_to '<button type="button">All Paintings</button>'.html_safe, paintings_path %>

<%= link_to '<button type="button">All Artists</button>'.html_safe, artists_path %>

class-work/museum_app/app/views/artists/create.html.erb
<h1>Artists#create</h1>
<p>Find me in app/views/artists/create.html.erb</p>

class-work/museum_app/app/views/artists/edit.html.erb
<h1>Artists#edit</h1>
<p>Find me in app/views/artists/edit.html.erb</p>

class-work/museum_app/app/views/artists/index.html.erb
<%= render partial: "app_homes/nav" %>

<table class="table">
	<tr>
		<th>Name</th>
		<th>Hometown</th>
		<th>Date of Birth</th>
	</tr>
	<% @artists.each do |artist| %>
		<tr class="story-row">
			<td>
				<%= artist.name %>
			</td>
			<td>
				<%= artist.hometown %>
			</td>
			<td>
				<%= artist.birth %>
			</td>
			<td>
				<%= link_to 'Paintings', artist_path(artist) %>
			</td>
		</tr>
	<% end %>
</table>

class-work/museum_app/app/views/artists/new.html.erb
<h1>Artists#new</h1>
<p>Find me in app/views/artists/new.html.erb</p>

class-work/museum_app/app/views/artists/show.html.erb
<%= render partial: "app_homes/nav" %>

<h2>Artist Profile</h2>
<h3><em><%= @artist.name %></em> from <em><%= @artist.hometown %></em> and born in<em><%= @artist.birth %></em></h3>


<table class="table">
	<tr>
		<th>Painting</th>
		<th>Title</th>
		<th>Year</th>
		<th>Museum</th>
	</tr>
	<% @paintings.each do |painting| %>
		<tr class="story-row">
			<td>
				<%= image_tag(painting.image_url, width: "100px") %>
			</td>
			<td>
				<%= painting.title %>
			</td>
			<td>
				<%= painting.year %>
			</td>
			<td>
				<%= link_to Museum.find(painting.museum_id).name, museum_path(painting.museum_id) %>
			</td>
		</tr>
	<% end %>
</table>

class-work/museum_app/app/views/artists/update.html.erb
<h1>Artists#update</h1>
<p>Find me in app/views/artists/update.html.erb</p>

class-work/museum_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MuseumApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>